# Generated by Django 4.1.5 on 2023-01-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_artist_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='members',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
