# Generated by Django 4.1.5 on 2023-01-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_artist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='release_date',
        ),
        migrations.AddField(
            model_name='album',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(blank=True, choices=[('AM', 'Alternative Metal'), ('AR', 'Alternative Rock'), ('RK', 'Rock'), ('MT', 'Metal')], max_length=2, null=True),
        ),
    ]
