# Generated by Django 4.1.5 on 2023-01-04 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_remove_album_release_date_album_release_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='date_formed',
        ),
        migrations.AddField(
            model_name='artist',
            name='year_formed',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023), django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023), django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)]),
        ),
    ]
