# Generated by Django 4.1.5 on 2023-01-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_alter_song_album_alter_song_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
    ]
