# Generated by Django 4.1.5 on 2023-01-05 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_remove_album_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='release_year',
        ),
        migrations.AddField(
            model_name='album',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
